== REST Template for Golang

=== Requirements
 - *_Go version :_* 1.12 or newer
 - *_OS :_* Linux
 - *_Git version :_* 2.0 or newer

=== Preparing the environment
Download go binaries in /tmp folder
[source,shell]
----
wget -P /tmp https://dl.google.com/go/go1.12.6.linux-amd64.tar.gz
sha256sum /tmp/go1.12.6.linux-amd64.tar.gz

dbcf71a3c1ea53b8d54ef1b48c85a39a6c9a935d01fc8291ff2b92028e59913c  go1.12.6.linux-amd64.tar.gz
----
Remove current go installation
[source,shell]
----
sudo mv /usr/local/go /tmp/
----
Install go
[source,shell]
----
sudo tar -xvf /tmp/go1.12.6.linux-amd64.tar.gz -C /usr/local
sudo chown -R root:root /usr/local/go
----
Set ENV variables
command line or ~/.profile ~/.bashrc ... 
[source,shell]
----
# Go Root
export GOROOT=/usr/local/go

# Go Path
export GOPATH=$HOME/projects/golang

# PATH
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
----
Load the new changes
[source,shell]
----
source ~/.profile
----

=== Workspace 
Until the release of *Go 1.11* all Go projects had to be created in *$GOPATH* which contains the following sub directories : 

1. *$GOPATH/src* : Contains all Go source files.
2. *$GOPATH/bin* : It's where Go tool builds and installs binaries.
3. *$GOPATH/pkg* : The folder of the Go package archives

=== Hello World
Create and move to project source files folder
[source,go]
----
mkdir -p $GOPATH/src/github.com/your_username/hello  && cd "$_"
----

Create _hello-world.go_ with the following content. 
[source,go]
----
package main

import "fmt"

func main() {
  fmt.Println("hello world")
}
----
Run the program
[source,go]
----
go run hello-world.go
----
Create binary
[source,go]
----
go build hello-world.go
----
Run the binary
[source,go]
----
./hello-world.go
----

=== Hello world web
Create and move to project source files folder
[source,shell]
----
mkdir -p $GOPATH/src/github.com/your_username/hello-web  && cd "$_"
----
Create _hello-world-web.go_ with the following content. 
[source,go]
----
package main

import (
    "fmt"
    "net/http"
)

func helloWorld(w http.ResponseWriter, r *http.Request){
    fmt.Fprintf(w, "Hello World")
}

func main() {
    http.HandleFunc("/", helloWorld)
    http.ListenAndServe(":8080", nil)
}
----
